about/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.about_kayaking, name='about_kayaking'),
    path('contact_kayaker/', views.contact_kayaker, name='contact_kayaker'),
    path('contact/success/', views.contact_success, name='contact_success'),
]

blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('user_profile/', views.userprofile, name='user_profile'),
    path('profile_edit/', views.profile_edit, name='profile_edit'),
    path('delete_profile/', views.delete_profile, name='delete_profile'),
    path(
        'delete_profile_picture/',
        views.delete_profile_picture, name='delete_profile_picture'),
    path('post_detail/<slug:slug>/', views.post_detail, name='post_detail'),
    path(
        'post/new/',
        views.Create_Kayak_Post_View.as_view(), name='create_kayak_post'),
    path(
        'post/<slug:slug>/edit/',
        views.Update_Kayak_Post_View.as_view(), name='update_kayak_post'),
    path(
        'post/<slug:slug>/delete/',
        views.Delete_Kayak_Post_View.as_view(), name='delete_kayak_post'),
    path('my-posts/', views.My_Post_List_View.as_view(), name='my_post_list'),
    path('search/', views.kayak_search_result, name='kayak_search_result'),
    path(
        'post/<slug:slug>/add_comment/',
        views.add_comment, name='add_comment'),
    path(
        'comment/<int:comment_id>/edit/',
        views.edit_comment, name='edit_comment'),
    path(
        'comment/<int:comment_id>/delete/',
        views.delete_comment, name='delete_comment'),

    path(
        'post/<slug:slug>/',
        views.kayak_toggle_favorite, name='kayak_toggle_favorite')

]

kayak_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views as index_views
from about import views as about_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', include('about.urls')),
    path("accounts/", include("allauth.urls")),
    path('', include("blog.urls"), name='blog-urls'),

]

"""
This is for the 404 and 500 page handler.
"""
handler404 = 'kayak_blog.views.handler404'
handler500 = 'kayak_blog.views.handler500'

about/models.py
from django.db import models

# Create your models here.


class ContactInquiry(models.Model):
    """
    This is a model for a user to
    make contact with the blog site.
    The user will supply details name,
    email and message.
    """
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Inquiry from {self.name} - {self.email}'

about/forms.py
from django import forms
from .models import ContactInquiry


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactInquiry
        fields = ['name', 'email', 'message']

about/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.contrib import messages


def about_kayaking(request):
    """
    Returns the about kayaking page and
    display relevant information.
    """

    return render(request, 'about/about.html')


def contact_kayaker(request):
    """
    Allows a user to get in touch with the blog.
    Using a form the user send a message with their details.
    about/contact_kayaker.html template used.
    """
    form = ContactForm()

    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(
                request,
                'Your message has been received successfully!')

            return redirect('about_kayaking')
        else:
            messages.error(request, 'Error submitting your message.')
            # form = ContactForm()

    return render(request, 'about/contact_kayaker.html', {'form': form})


def contact_success(request):
    return render(request, 'about/contact_success.html')

about/templates/about/about.html
{%extends 'base.html'%}
{% load static %}
{%load crispy_forms_tags%}

{%block content %}

<div class="container mt-5">
  <div class="row">

  </div>
  <div class="row align-items-center">
    <div class="col-md-7">
      <img src="/static/images/about.jpg" alt="Kayaker paddling image" class="img-fluid"
        style="height: auto; width: 100%;">
    </div>
    <div class="col-md-5">

      <h1 class="text-right"> About Our Kayaking Blog</h1>
      <p class="text-right">Welcome to our kayaking blog! We are passionate kayakers dedicated to sharing our adventures
        and insights.</p>

      <p>Our blog features a variety of content including:</p>
      <ul>
        <li><strong>Kayaking Tips:</strong> Learn the best practices for a safe and enjoyable kayaking experience.</li>
        <li><strong>Gear Reviews:</strong> Find reviews on the latest kayaking equipment and accessories.</li>
        <li><strong>Trip updates:</strong> Read about our kayaking adventures and get inspired for your next trip.</li>
      </ul>
      <p>Join us as we explore the beauty of nature from the water. Whether you're a seasoned kayaker or just starting
        out, there's something here for everyone!</p>

      <p class="text-right">Feel free to <a href="{% url 'contact_kayaker' %}">Contact Us</a> with any questions or
        comments.</p>
    </div>


  </div>

</div>

{%endblock content%}

about/templates/about/contact_kayaker.html
{%extends 'base.html'%}
{% load static %}
{%load crispy_forms_tags%}

{%block content %}

<div class="container mt-5">
  <h1 class="text-center">Contact Us</h1>
  {% if messages %}
  <div class="alert alert-custom">

    {% for message in messages %}
    {{ message }}
    {% endfor %}

  </div>
  {% endif %}

  <form method="post" class="kayak_contact_form">
    {% csrf_token %}
    <div class="mb-3">
      <label for="id_name" class="form-label"><i class="fa-solid fa-circle-user"></i></label>
      {{ form.name|as_crispy_field}}
    </div>
    <div class="mb-3">
      <label for="id_email" class="form-label"><i class="fa-solid fa-envelope-open"></i></label>
      {{ form.email|as_crispy_field }}
    </div>
    <div class="mb-3">
      <label for="id_message" class="form-label"><i class="fa-regular fa-comment-dots"></i></label>
      {{ form.message|as_crispy_field }}
    </div>
    <button type="submit" class="btn btn-outline-success">Send Message</button>
  </form>
</div>

{%endblock content%}

about/templates/about/contact_us.html
{%extends 'base.html'%}
{% load static %}
{%load crispy_forms_tags%}

{%block content %}

<div class="container mt-5">
  <h1 class="text-center">Contact Us</h1>
  {% if messages %}
  <div class="alert alert-custom">

    {% for message in messages %}
    {{ message }}
    {% endfor %}

  </div>
  {% endif %}

  <form method="post" class="kayak_contact_form">
    {% csrf_token %}
    <div class="mb-3">
      <label for="id_name" class="form-label"><i class="fa-solid fa-circle-user"></i></label>
      {{ form.name|as_crispy_field}}
    </div>
    <div class="mb-3">
      <label for="id_email" class="form-label"><i class="fa-solid fa-envelope-open"></i></label>
      {{ form.email|as_crispy_field }}
    </div>
    <div class="mb-3">
      <label for="id_message" class="form-label"><i class="fa-regular fa-comment-dots"></i></label>
      {{ form.message|as_crispy_field }}
    </div>
    <button type="submit" class="btn btn-outline-success">Send Message</button>
  </form>
</div>

{%endblock content%}